config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :movies

  resources :theaters

 root 'welcome#index'

end

app/models/movie.rb
# == Schema Information
#
# Table name: movies
#
#  id              :integer          not null, primary key
#  name            :string
#  rating          :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  theater_id      :integer
#  currentviewings :string
#  avatar          :string
#

class Movie < ActiveRecord::Base

  belongs_to :theater
  mount_uploader :avatar, AvatarUploader

# Validators
  validates :name, presence: true
  validates :rating, presence: true
  validates :currentviewings, presence: true
end

app/models/theater.rb
# == Schema Information
#
# Table name: theaters
#
#  id         :integer          not null, primary key
#  name       :string
#  location   :string
#  address    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Theater < ActiveRecord::Base
  has_many :movies
  has_many :viewers, :through => :movies
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  has_many :viewers
end

app/models/viewer.rb
# == Schema Information
#
# Table name: viewers
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  movie_id   :integer
#  user_id    :integer
#

class Viewer < ActiveRecord::Base
    belongs_to :movie
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


before_action :current_user

helper_method :current_user, :signed_in?

def current_user

  @current_user ||= User.find_by(name:'John')
end

def signed_in?
    return true if current_user.present?
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
    logger.debug "How Many Movies: #{@movies.size}"
    logger.debug @movies.inspect
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :rating, :theater_id, :currentviewings, :avatar, :listing_ids)
    end
end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  before_action :set_theater, only: [:show, :edit, :update, :destroy]

  # GET /theaters
  # GET /theaters.json
  def index
    @theaters = Theater.all
  end

  # GET /theaters/1
  # GET /theaters/1.json
  def show
  end

  # GET /theaters/new
  def new
    @theater = Theater.new
  end

  # GET /theaters/1/edit
  def edit
  end

  # POST /theaters
  # POST /theaters.json
  def create
    @theater = Theater.new(theater_params)

    respond_to do |format|
      if @theater.save
        format.html { redirect_to @theater, notice: 'Theater was successfully created.' }
        format.json { render :show, status: :created, location: @theater }
      else
        format.html { render :new }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theaters/1
  # PATCH/PUT /theaters/1.json
  def update
    respond_to do |format|
      if @theater.update(theater_params)
        format.html { redirect_to @theater, notice: 'Theater was successfully updated.' }
        format.json { render :show, status: :ok, location: @theater }
      else
        format.html { render :edit }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theaters/1
  # DELETE /theaters/1.json
  def destroy
    @theater.destroy
    respond_to do |format|
      format.html { redirect_to theaters_url, notice: 'Theater was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theater
      @theater = Theater.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theater_params
      params.require(:theater).permit(:name, :location, :address, :theater_id, :movie_ids => [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assign35</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet' type='text/css'>
</head>
<body>

<div>
  <% if signed_in? %>
    <p class="navbar-text navbar-right"><strong>Signed in as</strong> <%= link_to current_user.name %></p>
  <% end %>
</div>
<%= yield %>



</body>
</html>

app/views/movies/_form.html.erb
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>



    <%= form_for @movie, html: { multipart: true } do |f| %>
  <div>

    <%= f.file_field :avatar %>
    <%= image_tag(@movie.avatar_url) %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :theater %><br>
    <%= f.select :theater_id, Theater.all.collect {|p| [ p.name, p.id] }, {include_blank: 'None'} %>
  </div>
  <div class="field">
    <%= f.label :currentviewings %><br>
    <%= f.text_field :currentviewings %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<table class="table">
  <thead>
    <tr>
      <th>Logo</th>
      <th>Name</th>
      <th>Rating</th>
      <th>Current Viewings</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>


      <tr>
        <td><%= image_tag movie.avatar_url(:thumb) %></td>
        <td><%= movie.name %></td>
        <td><%= movie.rating %></td>
        <td><%= movie.currentviewings %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<footer><%= link_to 'Home Page', root_path %></footer>
<footer><%= link_to 'New Movie', new_movie_path %></footer>
<footer><%= link_to 'Theater Page', '/theaters' %></footer>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo</strong>
<%= image_tag @movie.avatar_url(:profile) %>
</p>
<p>
  <strong>Name:</strong>
  <%= @movie.name %> <br><br>
</p>

<p>
  <strong>Rating:</strong>
  <%= @movie.rating %>
</p>

<p>
  <strong>Current Viewings:</strong>
  <%= @movie.currentviewings %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/theaters/_form.html.erb
<%= form_for(@theater) do |f| %>
  <% if @theater.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theater.errors.count, "error") %> prohibited this theater from being saved:</h2>

      <ul>
      <% @theater.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>


  <div class="field">
    <%= hidden_field_tag "theater[movie_ids][]", nil %>
    <% Movie.all.each do |movie| %>
      <%= check_box_tag "theater[movie_ids][]", movie.id, @theater.movie_ids.include?(movie.id) %>
      <%= movie.name %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/theaters/edit.html.erb
<h1>Editing Theater</h1>

<%= render 'form' %>

<%= link_to 'Show', @theater %> |
<%= link_to 'Back', theaters_path %>

app/views/theaters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Theaters</h1>

<table class="table">
  <thead>
    <tr>
      <th>Theater Name</th>
      <th>Location</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @theaters.each do |theater| %>
      <tr>
        <td><%= theater.name %></td>
        <td><%= theater.location %></td>
        <td><%= theater.address %></td>
        <td><%= link_to 'Show', theater %></td>
        <td><%= link_to 'Edit', edit_theater_path(theater) %></td>
        <td><%= link_to 'Destroy', theater, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>





<footer><%= link_to 'Home', root_path %></footer>
<footer><%= link_to 'New Theater', new_theater_path %></footer>
<footer><%= link_to 'Back to Movie Page', '/movies' %></footer>

app/views/theaters/new.html.erb
<h1>New Theater</h1>

<%= render 'form' %>

<%= link_to 'Back', theaters_path %>

app/views/theaters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @theater.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @theater.location %>
</p>

<p>
  <strong>Address:</strong>
  <%= @theater.address %>
</p>

<p>
  <strong>Movies</strong>
  <ul>
    <% @theater.movies.each do |movie| %>
      <li><%= movie.name %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_theater_path(@theater) %> |
<%= link_to 'Back', theaters_path %>

app/views/users/new.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/welcome/index.html.erb
<button type="button" class="btn btn-success"><%= link_to "Home", root_path %></button>
<button type="button" class="btn btn-warning"><%= link_to "Movies", movies_path %></button>
<button type="button" class="btn btn-info"><%= link_to "Theaters", theaters_path %></button>




<h1>Welcome To My Movie Log Site. Click <strong><%= link_to "here", "/movies" %></strong> To Continue. Click <strong><%= link_to "here", "/theaters" %></strong> To Look For Theaters.</h1>


<p class="lead">Hac nam a a id mollis iaculis hac condimentum montes a porta est molestie vehicula ante ultricies sit netus mauris turpis. Mattis elit parturient est vel fermentum pharetra lectus scelerisque augue adipiscing ipsum ad mattis non volutpat faucibus ullamcorper suspendisse placerat risus vestibulum aliquet at massa dictum molestie bibendum. Nunc habitasse sit massa penatibus ultrices a a a a iaculis aenean a adipiscing eget proin ultrices hac vitae a litora. At suspendisse viverra montes ligula auctor at tempor maecenas a quisque enim dictum est suspendisse ullamcorper mi a ullamcorper vestibulum enim donec dui. Orci id varius venenatis parturient parturient suspendisse convallis cras quis mi commodo a vitae mollis habitant justo blandit non porttitor a phasellus parturient ac suspendisse at adipiscing scelerisque. Praesent ut nibh metus tincidunt sagittis semper venenatis dis venenatis blandit faucibus nam dui fringilla parturient.

Lacinia urna nulla egestas penatibus non mi cubilia hendrerit consequat a nascetur adipiscing ipsum a condimentum suspendisse non. Hendrerit erat mi purus porttitor vestibulum a quis fringilla a risus et magna adipiscing a a dolor ligula bibendum fermentum sem vestibulum non cras porta aptent a ullamcorper quam. Parturient a orci nam blandit molestie lacinia est adipiscing mattis vulputate ullamcorper suspendisse at nulla nisl arcu cum cubilia massa vestibulum dui mi enim scelerisque lorem parturient ullamcorper iaculis. Nibh fermentum a adipiscing id senectus ad hac sociosqu cum sem diam orci nullam id nec per a commodo. Neque neque euismod auctor consectetur condimentum ac phasellus dignissim metus ac nisl cum justo nam a a lorem auctor nostra consectetur.

Fermentum diam adipiscing penatibus mus venenatis tempor aliquet adipiscing sed a mi ac sit nec vestibulum nisi. A erat pharetra consectetur pharetra dictumst sed lobortis nulla in adipiscing a a lectus elit parturient donec ornare a amet. Adipiscing at mus parturient a adipiscing hac arcu parturient integer massa tincidunt vestibulum per lacus ultrices a arcu habitant semper tempor scelerisque eros volutpat adipiscing a imperdiet.</p>